name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main  # deployment branch
  workflow_dispatch:  # manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: 📦 Restore dependencies
        run: dotnet restore

      - name: 🔨 Build
        run: dotnet build --configuration Release --no-restore

      - name: 🧪 Run tests
        run: dotnet test --no-build --verbosity normal

      - name: 📤 Publish app
        run: dotnet publish -c Release -o ./publish

      - name: 🚀 Deploy to Lightsail & Restart App
        run: |
          echo "🔐 Setting up SSH key"
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "📁 Ensuring remote temp directory exists"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} "sudo mkdir -p /opt/olu_backend/{app,temp} && sudo chown -R \$USER:\$USER /opt/olu_backend"

          echo "📡 Uploading build files to server"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./publish/ \
            ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:/opt/olu_backend/temp/

          echo "🌀 Restarting app on server"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            set -e
            echo "🔁 Cleaning previous deployment..."
            sudo systemctl stop kestrel-oluapp
            rm -rf /opt/olu_backend/app/*
            mv /opt/olu_backend/temp/* /opt/olu_backend/app/

            echo "🚦 Restarting kestrel-oluapp service"
            sudo systemctl daemon-reexec
            sudo systemctl restart kestrel-oluapp
            echo "✅ App restarted successfully"
            echo "Service Deployed Smoothly"
          EOF
