name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: 📦 Restore dependencies (inside /source)
        working-directory: ./source
        run: dotnet restore

      - name: 🔨 Build for validation (inside /source)
        working-directory: ./source
        run: dotnet build --configuration Release --no-restore

      - name: 🧪 Run tests (if any)
        working-directory: ./source
        run: dotnet test --no-build --verbosity normal || echo "No tests found, skipping..."

      - name: 📅 Auto-generate EF migration (optional)
        working-directory: ./source
        run: |
          dotnet tool install --global dotnet-ef
          export PATH="$PATH:/home/runner/.dotnet/tools"
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          if dotnet ef migrations add AutoMigration_$TIMESTAMP --no-build; then
            echo "✅ New migration added: AutoMigration_$TIMESTAMP"
          else
            echo "ℹ️ No EF Core changes detected. Continuing..."
          fi

      - name: 📥 Commit migration (if any)
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add source/Migrations || true
          git diff --cached --quiet || git commit -m "🔁 Auto-generated EF migration"
          git push || echo "ℹ️ Nothing to push."

      - name: 🪄 Ensure config casing is correct
        run: |
          if [ -f "source/appsettings.production.json" ]; then
            mv source/appsettings.production.json source/appsettings.Production.json
          fi

      - name: 🚀 Deploy to Lightsail with Docker Compose
        run: |
          echo "🔐 Setting up SSH key"
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "📁 Ensure remote directory exists"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} \
            "sudo mkdir -p /opt/olu_backend && sudo chown -R \$USER:\$USER /opt/olu_backend"

          echo "📤 Uploading app/ and source/ to remote server"
          rsync -avz --delete \
            --exclude 'bin' --exclude 'obj' --exclude '.git' \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./app ./source ./Dockerfile \
            ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:/opt/olu_backend/

          echo "🐳 Rebuilding containers remotely"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            set -e
            cd /opt/olu_backend

            echo "🧼 Clean old containers/images"
            docker compose down || true
            docker builder prune -af || true
            docker system prune -af || true
            docker volume prune -f || true

            echo "🔧 Make script executable"
            chmod +x source/wait-for-it.sh || true

            echo "📦 Rebuild and start containers"
            docker compose build --no-cache
            docker compose up -d

            echo "✅ Deployment successful"
          EOF
