name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: 📦 Restore dependencies
        working-directory: source
        run: dotnet restore

      - name: 🔨 Build (Local Validation)
        working-directory: source
        run: dotnet build --configuration Release --no-restore

      - name: 🧪 Run tests
        working-directory: source
        run: dotnet test --no-build --verbosity normal || echo "No tests found, skipping..."

      - name: 📅 Auto-generate EF migration if model has changed
        working-directory: source
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          dotnet tool install --global dotnet-ef
          export PATH="$PATH:/home/runner/.dotnet/tools"
          
          echo "⚙️ Checking for EF Core model changes..."
          if dotnet ef migrations add AutoGeneratedMigration_$TIMESTAMP --no-build; then
            echo "✅ New migration created: AutoGeneratedMigration_$TIMESTAMP"
          else
            echo "ℹ️ No new EF Core model changes detected."
          fi

      - name: 📥 Commit migration (if any)
        working-directory: source
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add Migrations/ || true
          git diff --cached --quiet || git commit -m "🔁 Auto-generated EF migration"
          git push || echo "ℹ️ Nothing to push or push failed."

      - name: 🪄 Ensure config casing is correct (rename before deploy)
        working-directory: source
        run: |
          if [ -f "appsettings.production.json" ]; then
            echo "Renaming appsettings.production.json → appsettings.Production.json"
            mv -f appsettings.production.json appsettings.Production.json
          else
            echo "No lowercase config file found. Skipping rename."
          fi

      - name: 🚀 Deploy Full Source to Lightsail & Rebuild with Docker Compose
        run: |
          echo "🔐 Setting up SSH key"
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "📁 Ensuring remote project directory exists"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} \
            "sudo mkdir -p /opt/olu_backend/source && sudo chown -R \$USER:\$USER /opt/olu_backend"

          echo "📤 Uploading project files (excluding unnecessary)"
          rsync -avz --delete \
            --exclude 'bin' --exclude 'obj' --exclude '.git' \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./ \
            ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:/opt/olu_backend/source/

          echo "🐳 Running Docker Compose cleanup and rebuild on remote server"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            set -e
            cd /opt/olu_backend/source

            echo "🧼 Cleaning up old Docker images, volumes, and cache"
            chmod +x ./wait-for-it.sh
            docker compose down || true
            docker builder prune -af || true
            docker system prune -af || true
            docker volume prune -f || true

            echo "📦 Rebuilding and restarting containers"
            docker compose build --no-cache
            docker compose up -d

            echo "✅ Deployment complete!"
          EOF
