name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main  # or your deployment branch
  workflow_dispatch:  # allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # adjust if needed

      - name: 📦 Restore dependencies
        run: dotnet restore

      - name: 🔨 Build
        run: dotnet build --configuration Release --no-restore

      - name: 🧪 Run tests
        run: dotnet test --no-build --verbosity normal

      - name: 📤 Publish app
        run: dotnet publish -c Release -o ./publish

      - name: 🚀 Deploy to Lightsail and Restart App
        run: |
          echo "🔐 Setting up SSH key"
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "📡 Uploading build files to temp directory"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./publish/ \
            ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }}:/var/www/olu_olu_backend/temp/

          echo "🌀 Restarting app on server"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} << 'EOF'
            set -e

            echo "🔁 Cleaning previous deployment..."
            rm -rf /var/www/olu_backend/app/*
            mv /var/www/olu_backend/temp/* /var/www/olu_backend/app/

            echo "🚦 Restarting kestrel-oluapp service"
            sudo systemctl restart kestrel-oluapp
            chmod +x setup-kestrel-oluapp.sh
            ./setup-kestrel-oluapp.sh
            echo "✅ App restarted successfully"
          EOF
